package com.lutfy.ticketfy.audit;

public enum AuditAction {
    PAYOUT_ACCOUNT_SAVED,
    PAYOUT_REQUESTED,
    PAYOUT_SENT_TO_REVIEW,
    PAYOUT_APPROVED,
    PAYOUT_REJECTED,
    PAYOUT_CANCELLED,
    PAYOUT_PAID,
    PAYOUT_FAILED,
    PAYOUTS_BLOCKED,
    PAYOUTS_UNBLOCKED,
    EVENT_FEATURED,
    EVENT_UNFEATURED,
    TICKET_TYPE_PRICE_CHANGED,
    EVENT_CANCELLED
}
